---
- name: Build and Start Docker Container
  hosts: localhost
  
  vars:
  - docker_image_name: "ssh_os"
  - docker_container_name: "server"
  - patting_ssh_port: "1234"
  - patting_http_port: "80"
  
  tasks:

  - copy:
     src: "Dockerfile"
     dest: "./BuildImage/"

  - copy:
     src: "containerkey.pub"
     dest: "./BuildImage/"

  - name: "Build docker image from Dockerfile"
    docker_image:
       name:  "{{docker_image_name}}"
       build:
         pull: yes
         path: "./"
       state: present
       source: build
  
  - name: Start Docker container
    docker_container:
      container_default_behavior: compatibility
      name: "{{docker_container_name}}"
      image: "{{docker_image_name}}"
      ports: 
        - 127.0.0.1:1234:22
        - 127.0.0.1:8888:80
    register: docker_info
    
#  - name: "Update inventory file"
#    lineinfile:
#      path: inventory
#      insertafter: '^\[container]'
#      firstmatch: yes
#      line: "{{docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress}}"
#      state: present

  - name: Add Docker host to group container
    add_host:
      name: "{{docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress}}"
      groups: container

- name: Status container
  hosts: container
  tasks:
   - ping:
   
   - name: Install & Start Nginx
     apk:
      name:  nginx
   - copy:
      src: "default.conf"
      dest: "/etc/nginx/http.d/"
   - service:
      name: nginx
      state: started
      enabled: yes

   - template:
      src: "index.j2"
      dest: "/var/www/localhost/htdocs/index.html"
