---
- name: Build and Start Docker Container
  hosts: localhost
  
  vars:
  - docker_image_name: "ssh_os"
  - docker_container_name: "server"
  
  tasks:

  - name: "Build docker image from Dockerfile"
    docker_image:
       name:  "{{docker_image_name}}"
       build:
        pull: yes
        path: "./"
       state: present
       source: build

  - name: Start Docker container
    docker_container:
      container_default_behavior: compatibility
      name: "{{docker_container_name}}"
      image: "{{docker_image_name}}"
      ports: 
        - 127.0.0.1:1234:22
        - 127.0.0.1:8888:80
    register: docker_info

  - name: Add Docker host to group container
    add_host:
#      name: '{{docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress}}'
      name: '{{docker_info.container.NetworkSettings.IPAddress}}'
#      name: '172.17.0.2'
      groups: container

  - file:
     dest: 'containerkey'
     mode: '600'

- name: Setup Nginx and Deploy Web
  hosts: container

  tasks:

  - name: Install & Start Nginx
    apk:
      name: nginx
  - name: Update Nginx default config
    copy:
      src: "default.conf"
      dest: "/etc/nginx/http.d/"
  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: yes
  - name: Deploy webpage
    template:
      src: "index.j2"
      dest: "/var/www/localhost/htdocs/index.html"
